[workspace]
members = [
    "crates/buffer-reader",
    "crates/processor",
    "crates/handler",
    "crates/sc",
    ".",
]

[package]
name = "sc-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
buffer-reader = { path = "crates/buffer-reader" }
processor = { path = "crates/processor" }
handler = { path = "crates/handler" }
sc = { path = "crates/sc" }
shared = { path = "crates/shared" }
